### ISSUE TITLE
Level 34 unsolvable

### ISSUE THREAD

**Issue by h4ckerle** [LolHens/Pushy-Reloaded#2]

**Comment by Joshix-1** [comment]
I found 2 times the same solution: 
https://www.yog.ch/pushy/pdf-druck/031-040.pdf
http://www.pushy-forum.de/viewtopic.php?t=11

They both don't work.

**Comment by schrmh** [comment]
I guess that in the original the trigger-able wall doesn't go up when something is on it.
So in that case it would be an implementation error of this port and there might be other unsolvable levels.

**Comment by LolHens** [comment]
oops let me check this

**Comment by h4ckerle** [comment]
Ah, thanks... I had only figured out about the JS setLevel () function...

**Comment by LolHens** [comment]
fixed by b6c7faaf76db8b4568c99485dab06c915d5bcddb
Release will follow shortly

**Comment by LolHens** [comment]
The page is now updated. You might need to press `Ctrl` + `F5` to clean the cache.
