### ISSUE TITLE
save current level to local storage

### ISSUE THREAD

**Issue by Joshix-1** [LolHens/Pushy-Reloaded#3]
This would allow users to start from where they left.

**Comment by LolHens** [comment]
I thought about just saving the current level in the url. What do you think?

**Comment by LolHens** [comment]
This would also somewhat solve #4

**Comment by Joshix-1** [comment]
#5 would also require local storage, but for #3 & #4 it would be a acceptable solution

**Comment by LolHens** [comment]
Fixed by bc7de7b59e1a9587b3dbec50d97fb9855481d939
Release will follow shortly

**Comment by LolHens** [comment]
The page is now updated. You might need to press `Ctrl` + `F5` to clean the cache.
